language: objective-c
branches:
  only:
    - v2
sudo: required
osx_image: xcode7.3
before_script:
  - npm install -g cordova
script:
  - cordova create testApp
  - git clone https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core ibm-bms-core-clone -b v2
  - cd testApp
  - cordova platform add ios
  - cordova plugin add ../ibm-bms-core-clone
  - cordova build ios
