language: android
branches:
  only:
    - v2
sudo: required
before_script:
  - npm install -g cordova
android:
  components:
  - android-23
script:
  - cordova create testApp
  - git clone https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core ibm-bms-core-clone -b v2
  - cd testApp
  - cordova platform add android
  - cordova plugin add ../ibm-bms-core-clone
  - cd platforms
  - pwd
  - ls
  - cd android
  - pwd
  - ls
  - sed
  - sed -i 's/minSdkVersion="14"/minSdkVersion="15"/' AndroidManifest.xml
  - cordova build android