language: android
branches:
  only:
    - v2
sudo: required
before_script:
  - npm install -g cordova
android:
  components:
  - android-23
script:
  - cordova create testApp
  - git clone https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core -b v2
  - pwd
  - ls
  - cd testApp
  - cordova platform add android
  - pwd
  - ls
  - cordova plugin add ../bms-clientsdk-cordova-plugin-core
  - pwd
  - ls
  - sed -i '' 's/minSdkVersion="14"/minSdkVersion="15"/' platforms/android/AndroidManifest.xml
  - cordova build android