language: android
branches:
  only:
    - v2
sudo: required
android:
  components:
    - android-23
before_script:
  - npm install -g cordova
script:
  - cordova create testApp
  - git clone https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core ibm-bms-core-clone -b v2
  - cd testApp
  - cordova platform add android
  - cordova plugin add ../ibm-bms-core-clone
  - cordova build android
